### ISSUE TITLE
Intermittently not working in notebook

### ISSUE THREAD

**Issue by n8henrie** [n8henrie/jupyter-black#2]
In windows, using notebook (not lab), it works *most* of the time but eventually stops working.

Just a tracking issue while I try to sort this out.

I *wonder* if it has to do with re-running cells, or perhaps cells that cause an error (e.g. black doesn't yet support `match`).

**Comment by n8henrie** [comment]
Also, if an users come across this, I'd appreciate if you can post here -- especially if you can reliably reproduce the issue!

**Comment by fny** [comment]
I actually copy and pasted your json into code prettifier and had a similar issue. I'll see if I can fix it. Also, I think for some reason your release is pinning the ipython and black version:

Collecting jupyter-black
  Downloading jupyter_black-0.3.1-py3-none-any.whl (7.7 kB)
Collecting black<23,>=21.9b0
  Downloading black-22.8.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 3.0 MB/s 
Collecting ipython<8,>=7.27.0
  Downloading ipython-7.34.0-py3-none-any.whl (793 kB)
     |████████████████████████████████| 793 kB 2.2 MB/s

**Comment by n8henrie** [comment]
I'm not using notebook anymore with any regularity. If anyone is seeing this issue and would like to reopen please let me know.
