### ISSUE TITLE
Proposal for removing defensive upper version constraints for transient dependencies

### ISSUE THREAD

**Issue by JakobGM** [n8henrie/jupyter-black#6]
- **Operating system and version**: MacOS / Linux.
- **Python version**: Python 3.9, 3.10, 3.11
- **jupyter-black version**: 0.3.1

## My Issue

Hi, Nathan, thanks for having created this package :bow: 

I [see](https://github.com/n8henrie/jupyter-black/blob/master/setup.cfg#L32) that you have put an upper version constraint `< 8` on ipython. This package therefore downgrades ipython for any dependents. I was just wondering if there any specific reason for why you have put the version constraint in place or not, is the current implementation incompatible with version 8 of the ipython API, or is it mainly a "defensive" constraint put in place before version 8 was released? :relaxed:

If it is the latter, a defensive upper constraint, might I suggest removing it? I will refer to [this great read](https://iscinumpy.dev/post/bound-version-constraints/) as my argument for doing so :nerd_face: 

Regardless what you decide, thanks in advance!
- Jakob

**Comment by n8henrie** [comment]
Your points are well taken. This was an experiment with upper version bounds (which I've never used in a project before), I appreciate you pointing out some downsides.

I'll cut a new version soon that should resolve this.

**Comment by n8henrie** [comment]
Should be resolved in ~0.3.2~ 0.3.3, which if everything passes should get pushed to PyPI by CI.

If you can confirm a fix would you mind closing?

**Comment by JakobGM** [comment]
That was a quick response, thanks a lot! It works 🎉
