### ISSUE TITLE
jupyter-black is not working in PyCharm

### ISSUE THREAD

**Issue by Rahkovsky** [n8henrie/jupyter-black#8]
Formatting Jupyter notebooks using jupyter-black does not work in PyCharm. The notebook begins with a cell:

```
%load_ext autoreload
%autoreload 2
import jupyter_black
jupyter_black.load()
```

However, executing this cell doesn't reformat the notebook. One [workaround](https://stackoverflow.com/questions/62477349/issue-using-black-formatter-in-pycharm) is to install the ```black``` extension in PyCharm. It would be ideal if jupyter-black worked seamlessly in PyCharm.

**Comment by n8henrie** [comment]
Thanks for your input. Unfortunately, I've never used pycharm and don't have plans to support it. Likewise, I don't use visual studio code for jupyter and wouldn't plan to support it either. I'll be happy to ping you if this changes. Alternatively, if you decide to implement it yourself, I'll happily look at the implementation and consider merging a PR.

**Comment by Rahkovsky** [comment]
Thank you for information.
